name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ 3.9 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: jupyverse-dev
        environment-file: dev-environment.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install jupyverse
      run: |
        pip install git+https://github.com/jupyter-server/fps
        pip install fps-uvicorn==0.0.2
        pip install . --no-deps
        pip install ./plugins/contents
        pip install ./plugins/auth
        pip install ./plugins/kernels
        pip install ./plugins/jupyterlab
        pip install flake8 black mypy pytest requests

    - name: Check style
      run: |
        black --check jupyverse plugins tests
        flake8 jupyverse plugins tests
        mypy jupyverse
        mypy plugins/contents
        mypy plugins/kernels
        mypy plugins/retrolab
        mypy plugins/auth
        mypy plugins/jupyterlab
        mypy plugins/nbconvert
        mypy plugins/yjs
        mypy plugins/terminals

    - name: Run tests
      run: |
        pytest ./tests -v
